//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZMind.Commodity.Test.CommodityServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestCommodity", Namespace="http://schemas.datacontract.org/2004/07/ZMind.Commodity.DTO.Request")]
    [System.SerializableAttribute()]
    public partial class RequestCommodity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsFuzzyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemCategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ZMind.Commodity.Test.CommodityServiceReference.ColumnOrder[] OrderByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageSizeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerIdField, value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsFuzzy {
            get {
                return this.IsFuzzyField;
            }
            set {
                if ((this.IsFuzzyField.Equals(value) != true)) {
                    this.IsFuzzyField = value;
                    this.RaisePropertyChanged("IsFuzzy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemCategoryId {
            get {
                return this.ItemCategoryIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemCategoryIdField, value) != true)) {
                    this.ItemCategoryIdField = value;
                    this.RaisePropertyChanged("ItemCategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemId {
            get {
                return this.ItemIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemIdField, value) != true)) {
                    this.ItemIdField = value;
                    this.RaisePropertyChanged("ItemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemName {
            get {
                return this.ItemNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemNameField, value) != true)) {
                    this.ItemNameField = value;
                    this.RaisePropertyChanged("ItemName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ZMind.Commodity.Test.CommodityServiceReference.ColumnOrder[] OrderBy {
            get {
                return this.OrderByField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderByField, value) != true)) {
                    this.OrderByField = value;
                    this.RaisePropertyChanged("OrderBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageIndex {
            get {
                return this.PageIndexField;
            }
            set {
                if ((this.PageIndexField.Equals(value) != true)) {
                    this.PageIndexField = value;
                    this.RaisePropertyChanged("PageIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize {
            get {
                return this.PageSizeField;
            }
            set {
                if ((this.PageSizeField.Equals(value) != true)) {
                    this.PageSizeField = value;
                    this.RaisePropertyChanged("PageSize");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ColumnOrder", Namespace="http://schemas.datacontract.org/2004/07/ZMind.Commodity.DTO.Request")]
    [System.SerializableAttribute()]
    public partial class ColumnOrder : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColumnNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAscField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ColumnName {
            get {
                return this.ColumnNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ColumnNameField, value) != true)) {
                    this.ColumnNameField = value;
                    this.RaisePropertyChanged("ColumnName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAsc {
            get {
                return this.IsAscField;
            }
            set {
                if ((this.IsAscField.Equals(value) != true)) {
                    this.IsAscField = value;
                    this.RaisePropertyChanged("IsAsc");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseCommodity", Namespace="http://schemas.datacontract.org/2004/07/ZMind.Commodity.DTO.Response")]
    [System.SerializableAttribute()]
    public partial class ResponseCommodity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ZMind.Commodity.Test.CommodityServiceReference.Commodity[] ResponseCommodityDetailListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ZMind.Commodity.Test.CommodityServiceReference.Commodity[] ResponseCommodityDetailList {
            get {
                return this.ResponseCommodityDetailListField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseCommodityDetailListField, value) != true)) {
                    this.ResponseCommodityDetailListField = value;
                    this.RaisePropertyChanged("ResponseCommodityDetailList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalCount {
            get {
                return this.TotalCountField;
            }
            set {
                if ((this.TotalCountField.Equals(value) != true)) {
                    this.TotalCountField = value;
                    this.RaisePropertyChanged("TotalCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Commodity", Namespace="http://schemas.datacontract.org/2004/07/ZMind.Commodity.DTO.Response")]
    [System.SerializableAttribute()]
    public partial class Commodity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BatIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BeginTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrandIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuyTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CouponUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreateUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DegreeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiscountRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisplayIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EdPropField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EndTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EveryoneSalesPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FactoryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ForPointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IfFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IfGiftsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IfOftenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IfServiceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageUrl2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageUrl3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageUrlFirstField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IntegralField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IntegralExchangeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IsEveryoneSalesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IsExchangeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IsGbField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IsIAlumniItemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IsOnlineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemCategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemCategoryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemDisplayIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemIntroduceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemNameEnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemNameShortField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemParaIntroduceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemRemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemSortDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemTypeDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemUnitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModifyTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModifyUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OffersTipsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PTypeCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Prop1NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Prop2DetailNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Prop2NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Prop3NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PyzjmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReturnAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoomDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoomImgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SalesPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SalesQtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ScanCodeIntegralField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SkuIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SkuPropId3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UseInfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BatId {
            get {
                return this.BatIdField;
            }
            set {
                if ((object.ReferenceEquals(this.BatIdField, value) != true)) {
                    this.BatIdField = value;
                    this.RaisePropertyChanged("BatId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BeginTime {
            get {
                return this.BeginTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.BeginTimeField, value) != true)) {
                    this.BeginTimeField = value;
                    this.RaisePropertyChanged("BeginTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BrandId {
            get {
                return this.BrandIdField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandIdField, value) != true)) {
                    this.BrandIdField = value;
                    this.RaisePropertyChanged("BrandId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuyType {
            get {
                return this.BuyTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.BuyTypeField, value) != true)) {
                    this.BuyTypeField = value;
                    this.RaisePropertyChanged("BuyType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CouponUrl {
            get {
                return this.CouponUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.CouponUrlField, value) != true)) {
                    this.CouponUrlField = value;
                    this.RaisePropertyChanged("CouponUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreateTime {
            get {
                return this.CreateTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.CreateTimeField, value) != true)) {
                    this.CreateTimeField = value;
                    this.RaisePropertyChanged("CreateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreateUserId {
            get {
                return this.CreateUserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CreateUserIdField, value) != true)) {
                    this.CreateUserIdField = value;
                    this.RaisePropertyChanged("CreateUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerIdField, value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataFrom {
            get {
                return this.DataFromField;
            }
            set {
                if ((object.ReferenceEquals(this.DataFromField, value) != true)) {
                    this.DataFromField = value;
                    this.RaisePropertyChanged("DataFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Degree {
            get {
                return this.DegreeField;
            }
            set {
                if ((object.ReferenceEquals(this.DegreeField, value) != true)) {
                    this.DegreeField = value;
                    this.RaisePropertyChanged("Degree");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiscountRate {
            get {
                return this.DiscountRateField;
            }
            set {
                if ((object.ReferenceEquals(this.DiscountRateField, value) != true)) {
                    this.DiscountRateField = value;
                    this.RaisePropertyChanged("DiscountRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayIndex {
            get {
                return this.DisplayIndexField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayIndexField, value) != true)) {
                    this.DisplayIndexField = value;
                    this.RaisePropertyChanged("DisplayIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EdProp {
            get {
                return this.EdPropField;
            }
            set {
                if ((object.ReferenceEquals(this.EdPropField, value) != true)) {
                    this.EdPropField = value;
                    this.RaisePropertyChanged("EdProp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.EndTimeField, value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EveryoneSalesPrice {
            get {
                return this.EveryoneSalesPriceField;
            }
            set {
                if ((object.ReferenceEquals(this.EveryoneSalesPriceField, value) != true)) {
                    this.EveryoneSalesPriceField = value;
                    this.RaisePropertyChanged("EveryoneSalesPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FactoryName {
            get {
                return this.FactoryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FactoryNameField, value) != true)) {
                    this.FactoryNameField = value;
                    this.RaisePropertyChanged("FactoryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ForPoints {
            get {
                return this.ForPointsField;
            }
            set {
                if ((object.ReferenceEquals(this.ForPointsField, value) != true)) {
                    this.ForPointsField = value;
                    this.RaisePropertyChanged("ForPoints");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gg {
            get {
                return this.GgField;
            }
            set {
                if ((object.ReferenceEquals(this.GgField, value) != true)) {
                    this.GgField = value;
                    this.RaisePropertyChanged("Gg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IfFlag {
            get {
                return this.IfFlagField;
            }
            set {
                if ((object.ReferenceEquals(this.IfFlagField, value) != true)) {
                    this.IfFlagField = value;
                    this.RaisePropertyChanged("IfFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IfGifts {
            get {
                return this.IfGiftsField;
            }
            set {
                if ((object.ReferenceEquals(this.IfGiftsField, value) != true)) {
                    this.IfGiftsField = value;
                    this.RaisePropertyChanged("IfGifts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IfOften {
            get {
                return this.IfOftenField;
            }
            set {
                if ((object.ReferenceEquals(this.IfOftenField, value) != true)) {
                    this.IfOftenField = value;
                    this.RaisePropertyChanged("IfOften");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IfService {
            get {
                return this.IfServiceField;
            }
            set {
                if ((object.ReferenceEquals(this.IfServiceField, value) != true)) {
                    this.IfServiceField = value;
                    this.RaisePropertyChanged("IfService");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageUrl {
            get {
                return this.ImageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageUrlField, value) != true)) {
                    this.ImageUrlField = value;
                    this.RaisePropertyChanged("ImageUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageUrl2 {
            get {
                return this.ImageUrl2Field;
            }
            set {
                if ((object.ReferenceEquals(this.ImageUrl2Field, value) != true)) {
                    this.ImageUrl2Field = value;
                    this.RaisePropertyChanged("ImageUrl2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageUrl3 {
            get {
                return this.ImageUrl3Field;
            }
            set {
                if ((object.ReferenceEquals(this.ImageUrl3Field, value) != true)) {
                    this.ImageUrl3Field = value;
                    this.RaisePropertyChanged("ImageUrl3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageUrlFirst {
            get {
                return this.ImageUrlFirstField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageUrlFirstField, value) != true)) {
                    this.ImageUrlFirstField = value;
                    this.RaisePropertyChanged("ImageUrlFirst");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Integral {
            get {
                return this.IntegralField;
            }
            set {
                if ((object.ReferenceEquals(this.IntegralField, value) != true)) {
                    this.IntegralField = value;
                    this.RaisePropertyChanged("Integral");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IntegralExchange {
            get {
                return this.IntegralExchangeField;
            }
            set {
                if ((object.ReferenceEquals(this.IntegralExchangeField, value) != true)) {
                    this.IntegralExchangeField = value;
                    this.RaisePropertyChanged("IntegralExchange");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IsEveryoneSales {
            get {
                return this.IsEveryoneSalesField;
            }
            set {
                if ((object.ReferenceEquals(this.IsEveryoneSalesField, value) != true)) {
                    this.IsEveryoneSalesField = value;
                    this.RaisePropertyChanged("IsEveryoneSales");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IsExchange {
            get {
                return this.IsExchangeField;
            }
            set {
                if ((object.ReferenceEquals(this.IsExchangeField, value) != true)) {
                    this.IsExchangeField = value;
                    this.RaisePropertyChanged("IsExchange");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IsGb {
            get {
                return this.IsGbField;
            }
            set {
                if ((object.ReferenceEquals(this.IsGbField, value) != true)) {
                    this.IsGbField = value;
                    this.RaisePropertyChanged("IsGb");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IsIAlumniItem {
            get {
                return this.IsIAlumniItemField;
            }
            set {
                if ((object.ReferenceEquals(this.IsIAlumniItemField, value) != true)) {
                    this.IsIAlumniItemField = value;
                    this.RaisePropertyChanged("IsIAlumniItem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IsOnline {
            get {
                return this.IsOnlineField;
            }
            set {
                if ((object.ReferenceEquals(this.IsOnlineField, value) != true)) {
                    this.IsOnlineField = value;
                    this.RaisePropertyChanged("IsOnline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemCategoryId {
            get {
                return this.ItemCategoryIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemCategoryIdField, value) != true)) {
                    this.ItemCategoryIdField = value;
                    this.RaisePropertyChanged("ItemCategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemCategoryName {
            get {
                return this.ItemCategoryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemCategoryNameField, value) != true)) {
                    this.ItemCategoryNameField = value;
                    this.RaisePropertyChanged("ItemCategoryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemCode {
            get {
                return this.ItemCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemCodeField, value) != true)) {
                    this.ItemCodeField = value;
                    this.RaisePropertyChanged("ItemCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemDisplayIndex {
            get {
                return this.ItemDisplayIndexField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemDisplayIndexField, value) != true)) {
                    this.ItemDisplayIndexField = value;
                    this.RaisePropertyChanged("ItemDisplayIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemId {
            get {
                return this.ItemIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemIdField, value) != true)) {
                    this.ItemIdField = value;
                    this.RaisePropertyChanged("ItemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemIntroduce {
            get {
                return this.ItemIntroduceField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemIntroduceField, value) != true)) {
                    this.ItemIntroduceField = value;
                    this.RaisePropertyChanged("ItemIntroduce");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemName {
            get {
                return this.ItemNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemNameField, value) != true)) {
                    this.ItemNameField = value;
                    this.RaisePropertyChanged("ItemName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemNameEn {
            get {
                return this.ItemNameEnField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemNameEnField, value) != true)) {
                    this.ItemNameEnField = value;
                    this.RaisePropertyChanged("ItemNameEn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemNameShort {
            get {
                return this.ItemNameShortField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemNameShortField, value) != true)) {
                    this.ItemNameShortField = value;
                    this.RaisePropertyChanged("ItemNameShort");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemParaIntroduce {
            get {
                return this.ItemParaIntroduceField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemParaIntroduceField, value) != true)) {
                    this.ItemParaIntroduceField = value;
                    this.RaisePropertyChanged("ItemParaIntroduce");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemRemark {
            get {
                return this.ItemRemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemRemarkField, value) != true)) {
                    this.ItemRemarkField = value;
                    this.RaisePropertyChanged("ItemRemark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemSortDesc {
            get {
                return this.ItemSortDescField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemSortDescField, value) != true)) {
                    this.ItemSortDescField = value;
                    this.RaisePropertyChanged("ItemSortDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemTypeDesc {
            get {
                return this.ItemTypeDescField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemTypeDescField, value) != true)) {
                    this.ItemTypeDescField = value;
                    this.RaisePropertyChanged("ItemTypeDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemUnit {
            get {
                return this.ItemUnitField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemUnitField, value) != true)) {
                    this.ItemUnitField = value;
                    this.RaisePropertyChanged("ItemUnit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifyTime {
            get {
                return this.ModifyTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.ModifyTimeField, value) != true)) {
                    this.ModifyTimeField = value;
                    this.RaisePropertyChanged("ModifyTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifyUserId {
            get {
                return this.ModifyUserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ModifyUserIdField, value) != true)) {
                    this.ModifyUserIdField = value;
                    this.RaisePropertyChanged("ModifyUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OffersTips {
            get {
                return this.OffersTipsField;
            }
            set {
                if ((object.ReferenceEquals(this.OffersTipsField, value) != true)) {
                    this.OffersTipsField = value;
                    this.RaisePropertyChanged("OffersTips");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PTypeCode {
            get {
                return this.PTypeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PTypeCodeField, value) != true)) {
                    this.PTypeCodeField = value;
                    this.RaisePropertyChanged("PTypeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PTypeId {
            get {
                return this.PTypeIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PTypeIdField, value) != true)) {
                    this.PTypeIdField = value;
                    this.RaisePropertyChanged("PTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Price {
            get {
                return this.PriceField;
            }
            set {
                if ((object.ReferenceEquals(this.PriceField, value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prop1Name {
            get {
                return this.Prop1NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Prop1NameField, value) != true)) {
                    this.Prop1NameField = value;
                    this.RaisePropertyChanged("Prop1Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prop2DetailName {
            get {
                return this.Prop2DetailNameField;
            }
            set {
                if ((object.ReferenceEquals(this.Prop2DetailNameField, value) != true)) {
                    this.Prop2DetailNameField = value;
                    this.RaisePropertyChanged("Prop2DetailName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prop2Name {
            get {
                return this.Prop2NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Prop2NameField, value) != true)) {
                    this.Prop2NameField = value;
                    this.RaisePropertyChanged("Prop2Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prop3Name {
            get {
                return this.Prop3NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Prop3NameField, value) != true)) {
                    this.Prop3NameField = value;
                    this.RaisePropertyChanged("Prop3Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pyzjm {
            get {
                return this.PyzjmField;
            }
            set {
                if ((object.ReferenceEquals(this.PyzjmField, value) != true)) {
                    this.PyzjmField = value;
                    this.RaisePropertyChanged("Pyzjm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Qty {
            get {
                return this.QtyField;
            }
            set {
                if ((object.ReferenceEquals(this.QtyField, value) != true)) {
                    this.QtyField = value;
                    this.RaisePropertyChanged("Qty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnAmount {
            get {
                return this.ReturnAmountField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnAmountField, value) != true)) {
                    this.ReturnAmountField = value;
                    this.RaisePropertyChanged("ReturnAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoomDesc {
            get {
                return this.RoomDescField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomDescField, value) != true)) {
                    this.RoomDescField = value;
                    this.RaisePropertyChanged("RoomDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoomImg {
            get {
                return this.RoomImgField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomImgField, value) != true)) {
                    this.RoomImgField = value;
                    this.RaisePropertyChanged("RoomImg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SalesPrice {
            get {
                return this.SalesPriceField;
            }
            set {
                if ((object.ReferenceEquals(this.SalesPriceField, value) != true)) {
                    this.SalesPriceField = value;
                    this.RaisePropertyChanged("SalesPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SalesQty {
            get {
                return this.SalesQtyField;
            }
            set {
                if ((object.ReferenceEquals(this.SalesQtyField, value) != true)) {
                    this.SalesQtyField = value;
                    this.RaisePropertyChanged("SalesQty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ScanCodeIntegral {
            get {
                return this.ScanCodeIntegralField;
            }
            set {
                if ((object.ReferenceEquals(this.ScanCodeIntegralField, value) != true)) {
                    this.ScanCodeIntegralField = value;
                    this.RaisePropertyChanged("ScanCodeIntegral");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SkuId {
            get {
                return this.SkuIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SkuIdField, value) != true)) {
                    this.SkuIdField = value;
                    this.RaisePropertyChanged("SkuId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SkuPropId3 {
            get {
                return this.SkuPropId3Field;
            }
            set {
                if ((object.ReferenceEquals(this.SkuPropId3Field, value) != true)) {
                    this.SkuPropId3Field = value;
                    this.RaisePropertyChanged("SkuPropId3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusDesc {
            get {
                return this.StatusDescField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusDescField, value) != true)) {
                    this.StatusDescField = value;
                    this.RaisePropertyChanged("StatusDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tel {
            get {
                return this.TelField;
            }
            set {
                if ((object.ReferenceEquals(this.TelField, value) != true)) {
                    this.TelField = value;
                    this.RaisePropertyChanged("Tel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UseInfo {
            get {
                return this.UseInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.UseInfoField, value) != true)) {
                    this.UseInfoField = value;
                    this.RaisePropertyChanged("UseInfo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CommodityServiceReference.ICommodityService")]
    public interface ICommodityService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommodityService/GetCommodity", ReplyAction="http://tempuri.org/ICommodityService/GetCommodityResponse")]
        ZMind.Commodity.Test.CommodityServiceReference.ResponseCommodity GetCommodity(ZMind.Commodity.Test.CommodityServiceReference.RequestCommodity request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommodityService/GetCommodity", ReplyAction="http://tempuri.org/ICommodityService/GetCommodityResponse")]
        System.Threading.Tasks.Task<ZMind.Commodity.Test.CommodityServiceReference.ResponseCommodity> GetCommodityAsync(ZMind.Commodity.Test.CommodityServiceReference.RequestCommodity request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICommodityServiceChannel : ZMind.Commodity.Test.CommodityServiceReference.ICommodityService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CommodityServiceClient : System.ServiceModel.ClientBase<ZMind.Commodity.Test.CommodityServiceReference.ICommodityService>, ZMind.Commodity.Test.CommodityServiceReference.ICommodityService {
        
        public CommodityServiceClient() {
        }
        
        public CommodityServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CommodityServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommodityServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommodityServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ZMind.Commodity.Test.CommodityServiceReference.ResponseCommodity GetCommodity(ZMind.Commodity.Test.CommodityServiceReference.RequestCommodity request) {
            return base.Channel.GetCommodity(request);
        }
        
        public System.Threading.Tasks.Task<ZMind.Commodity.Test.CommodityServiceReference.ResponseCommodity> GetCommodityAsync(ZMind.Commodity.Test.CommodityServiceReference.RequestCommodity request) {
            return base.Channel.GetCommodityAsync(request);
        }
    }
}
